name: Deploy to Live Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy files via SCP
      uses: appleboy/scp-action@v0.2.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}  # Use password instead of SSH private key
        source: "."
        target: "/home/winningwriters/winningwritersee4"

    - name: Run deployment script via SSH
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}  # Use password instead of SSH private key
        script: |
          cd /home/winningwriters/winningwritersee4
          git pull origin main
          # Add additional deployment commands like restarting services
